[package]
name = "noxirity/packeter"
description = "Combine all your HTTP requests into a singular Packet. Requires a Packeter Web Server."
license = "MIT"
authors = ["noxirity"]
version = "1.0.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]